server:
  port: 8088
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      authentication-database: admin
  application:
    name: "stockMonitoring"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=localhost;databaseName=stockMonitoring;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false

springdoc:
  swagger-ui:
    server-url: http://localhost:8088
    path: index.html
    enabled: true
    disable-swagger-default-url: true


