spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      authentication-database: admin
  application:
    name: "stockMonitoring"
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=172.30.23.136;databaseName=stockMonitoring;encrypt=true;trustServerCertificate=true;
    username: sa
    password: asd123!@#
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false

